TARGET = demo_plic

HBIRD_SDK_ROOT = ../../..

# Uncomment either option to enable optimization for code size
# extra -flto option will make code size smaller
# Option 1
#COMMON_FLAGS := -Os -msave-restore -fno-unroll-loops -flto
# Option 2
#COMMON_FLAGS := -Os -flto

SRCDIRS = .

INCDIRS = .

include $(HBIRD_SDK_ROOT)/Build/Makefile.base
